version: '3.8'

services:
  # 1. Backend Service Kamu (Golang)
  epod-service:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgresql://postgres.gvmknmaybejslbghzsov:HfuyrF1xd1iUVagY@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
      - KAFKA_BROKERS=kafka:29092 # Di dalam network docker, gunakan nama service + port internal
    depends_on:
      - kafka

  # 2. Zookeeper (Dibutuhkan oleh Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 3. Apache Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # Port ini agar laptopmu/host bisa akses ke Kafka jika diperlukan
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Mengatur dua listener: localhost untuk akses luar docker, kafka:29092 untuk sesama container docker
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1