// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../../mocks/mock_fleet_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "dispatch-fleet/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFleetRepository is a mock of FleetRepository interface.
type MockFleetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFleetRepositoryMockRecorder
}

// MockFleetRepositoryMockRecorder is the mock recorder for MockFleetRepository.
type MockFleetRepositoryMockRecorder struct {
	mock *MockFleetRepository
}

// NewMockFleetRepository creates a new mock instance.
func NewMockFleetRepository(ctrl *gomock.Controller) *MockFleetRepository {
	mock := &MockFleetRepository{ctrl: ctrl}
	mock.recorder = &MockFleetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFleetRepository) EXPECT() *MockFleetRepositoryMockRecorder {
	return m.recorder
}

// FindNearestAvailableCourier mocks base method.
func (m *MockFleetRepository) FindNearestAvailableCourier(ctx context.Context, pickup domain.Point, radiusMeters float64) (*domain.Courier, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearestAvailableCourier", ctx, pickup, radiusMeters)
	ret0, _ := ret[0].(*domain.Courier)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindNearestAvailableCourier indicates an expected call of FindNearestAvailableCourier.
func (mr *MockFleetRepositoryMockRecorder) FindNearestAvailableCourier(ctx, pickup, radiusMeters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearestAvailableCourier", reflect.TypeOf((*MockFleetRepository)(nil).FindNearestAvailableCourier), ctx, pickup, radiusMeters)
}

// GetCourierByID mocks base method.
func (m *MockFleetRepository) GetCourierByID(ctx context.Context, courierID string) (*domain.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierByID", ctx, courierID)
	ret0, _ := ret[0].(*domain.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierByID indicates an expected call of GetCourierByID.
func (mr *MockFleetRepositoryMockRecorder) GetCourierByID(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierByID", reflect.TypeOf((*MockFleetRepository)(nil).GetCourierByID), ctx, courierID)
}

// InsertCourier mocks base method.
func (m *MockFleetRepository) InsertCourier(ctx context.Context, courier *domain.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCourier", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCourier indicates an expected call of InsertCourier.
func (mr *MockFleetRepositoryMockRecorder) InsertCourier(ctx, courier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCourier", reflect.TypeOf((*MockFleetRepository)(nil).InsertCourier), ctx, courier)
}

// UpdateCourierStatus mocks base method.
func (m *MockFleetRepository) UpdateCourierStatus(ctx context.Context, courierID string, status domain.CourierStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourierStatus", ctx, courierID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourierStatus indicates an expected call of UpdateCourierStatus.
func (mr *MockFleetRepositoryMockRecorder) UpdateCourierStatus(ctx, courierID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourierStatus", reflect.TypeOf((*MockFleetRepository)(nil).UpdateCourierStatus), ctx, courierID, status)
}

// MockDispatchService is a mock of DispatchService interface.
type MockDispatchService struct {
	ctrl     *gomock.Controller
	recorder *MockDispatchServiceMockRecorder
}

// MockDispatchServiceMockRecorder is the mock recorder for MockDispatchService.
type MockDispatchServiceMockRecorder struct {
	mock *MockDispatchService
}

// NewMockDispatchService creates a new mock instance.
func NewMockDispatchService(ctrl *gomock.Controller) *MockDispatchService {
	mock := &MockDispatchService{ctrl: ctrl}
	mock.recorder = &MockDispatchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatchService) EXPECT() *MockDispatchServiceMockRecorder {
	return m.recorder
}

// AssignCourierToPickup mocks base method.
func (m *MockDispatchService) AssignCourierToPickup(ctx context.Context, pickupLocation domain.Point, radiusMeters float64) (*domain.AssignCourierResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourierToPickup", ctx, pickupLocation, radiusMeters)
	ret0, _ := ret[0].(*domain.AssignCourierResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourierToPickup indicates an expected call of AssignCourierToPickup.
func (mr *MockDispatchServiceMockRecorder) AssignCourierToPickup(ctx, pickupLocation, radiusMeters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourierToPickup", reflect.TypeOf((*MockDispatchService)(nil).AssignCourierToPickup), ctx, pickupLocation, radiusMeters)
}
