apiVersion: v1
kind: ConfigMap
metadata:
  name: settlement-config
  namespace: buroqet
  labels:
    app: settlement-service
data:
  db_host: "aws-1-ap-southeast-1.pooler.supabase.com"
  kafka_broker: "kafka:29092"
  app_port: "8085"
---
apiVersion: v1
kind: Secret
metadata:
  name: settlement-secret
  namespace: buroqet
  labels:
    app: settlement-service
type: Opaque
stringData:
  db_user: "postgres.gvmknmaybejslbghzsov"
  db_password: "HfuyrF1xd1iUVagY"
