// mocks/mock_tracking.go
// File ini berisi MOCK yang di-generate dari interface di domain/tracking.go.
// Dalam project nyata, ini di-generate otomatis dengan:
//   mockgen -source=internal/domain/tracking.go -destination=mocks/mock_tracking.go -package=mock_domain
//
// Karena kita menyimpan file ini di repo, CI/CD tidak perlu install mockgen.

// Code generated by MockGen. DO NOT EDIT.
// Source: tracking-service/internal/domain/tracking.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "tracking-service/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// ============================================================
// MockTrackingRepository — Mock untuk interface TrackingRepository
// ============================================================

// MockTrackingRepository is a mock of TrackingRepository interface.
type MockTrackingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingRepositoryMockRecorder
}

// MockTrackingRepositoryMockRecorder is the mock recorder for MockTrackingRepository.
type MockTrackingRepositoryMockRecorder struct {
	mock *MockTrackingRepository
}

// NewMockTrackingRepository creates a new mock instance.
func NewMockTrackingRepository(ctrl *gomock.Controller) *MockTrackingRepository {
	mock := &MockTrackingRepository{ctrl: ctrl}
	mock.recorder = &MockTrackingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackingRepository) EXPECT() *MockTrackingRepositoryMockRecorder {
	return m.recorder
}

// InsertEvent mocks base method.
func (m *MockTrackingRepository) InsertEvent(ctx context.Context, event *domain.TrackingEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockTrackingRepositoryMockRecorder) InsertEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "InsertEvent",
		reflect.TypeOf((*MockTrackingRepository)(nil).InsertEvent),
		ctx, event,
	)
}

// GetEventsByAWB mocks base method.
func (m *MockTrackingRepository) GetEventsByAWB(ctx context.Context, awb string) ([]domain.TrackingEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByAWB", ctx, awb)
	ret0, _ := ret[0].([]domain.TrackingEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByAWB indicates an expected call of GetEventsByAWB.
func (mr *MockTrackingRepositoryMockRecorder) GetEventsByAWB(ctx, awb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "GetEventsByAWB",
		reflect.TypeOf((*MockTrackingRepository)(nil).GetEventsByAWB),
		ctx, awb,
	)
}

// GetLatestEventByAWB mocks base method.
func (m *MockTrackingRepository) GetLatestEventByAWB(ctx context.Context, awb string) (*domain.TrackingEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestEventByAWB", ctx, awb)
	ret0, _ := ret[0].(*domain.TrackingEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestEventByAWB indicates an expected call of GetLatestEventByAWB.
func (mr *MockTrackingRepositoryMockRecorder) GetLatestEventByAWB(ctx, awb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "GetLatestEventByAWB",
		reflect.TypeOf((*MockTrackingRepository)(nil).GetLatestEventByAWB),
		ctx, awb,
	)
}

// ============================================================
// MockTrackingCache — Mock untuk interface TrackingCache
// ============================================================

// MockTrackingCache is a mock of TrackingCache interface.
type MockTrackingCache struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingCacheMockRecorder
}

// MockTrackingCacheMockRecorder is the mock recorder for MockTrackingCache.
type MockTrackingCacheMockRecorder struct {
	mock *MockTrackingCache
}

// NewMockTrackingCache creates a new mock instance.
func NewMockTrackingCache(ctrl *gomock.Controller) *MockTrackingCache {
	mock := &MockTrackingCache{ctrl: ctrl}
	mock.recorder = &MockTrackingCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackingCache) EXPECT() *MockTrackingCacheMockRecorder {
	return m.recorder
}

// SetStatus mocks base method.
func (m *MockTrackingCache) SetStatus(ctx context.Context, status *domain.TrackingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockTrackingCacheMockRecorder) SetStatus(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "SetStatus",
		reflect.TypeOf((*MockTrackingCache)(nil).SetStatus),
		ctx, status,
	)
}

// GetStatus mocks base method.
func (m *MockTrackingCache) GetStatus(ctx context.Context, awb string) (*domain.TrackingStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, awb)
	ret0, _ := ret[0].(*domain.TrackingStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockTrackingCacheMockRecorder) GetStatus(ctx, awb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "GetStatus",
		reflect.TypeOf((*MockTrackingCache)(nil).GetStatus),
		ctx, awb,
	)
}

// DeleteStatus mocks base method.
func (m *MockTrackingCache) DeleteStatus(ctx context.Context, awb string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStatus", ctx, awb)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStatus indicates an expected call of DeleteStatus.
func (mr *MockTrackingCacheMockRecorder) DeleteStatus(ctx, awb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "DeleteStatus",
		reflect.TypeOf((*MockTrackingCache)(nil).DeleteStatus),
		ctx, awb,
	)
}

// ============================================================
// MockKafkaProducer — Mock untuk interface KafkaProducer
// ============================================================

// MockKafkaProducer is a mock of KafkaProducer interface.
type MockKafkaProducer struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaProducerMockRecorder
}

// MockKafkaProducerMockRecorder is the mock recorder for MockKafkaProducer.
type MockKafkaProducerMockRecorder struct {
	mock *MockKafkaProducer
}

// NewMockKafkaProducer creates a new mock instance.
func NewMockKafkaProducer(ctrl *gomock.Controller) *MockKafkaProducer {
	mock := &MockKafkaProducer{ctrl: ctrl}
	mock.recorder = &MockKafkaProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaProducer) EXPECT() *MockKafkaProducerMockRecorder {
	return m.recorder
}

// PublishEvent mocks base method.
func (m *MockKafkaProducer) PublishEvent(ctx context.Context, topic, key string, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEvent", ctx, topic, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishEvent indicates an expected call of PublishEvent.
func (mr *MockKafkaProducerMockRecorder) PublishEvent(ctx, topic, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "PublishEvent",
		reflect.TypeOf((*MockKafkaProducer)(nil).PublishEvent),
		ctx, topic, key, value,
	)
}