# deployments/kubernetes/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse-config
  namespace: buroqet
  labels:
    app: warehouse-service
data:
  db_host: "GANTI.neon.tech"
  db_name: "wms_db"
  kafka_broker: "GANTI_DENGAN_UPSTASH_KAFKA_BROKER"
  app_port: "8080"
---
# Secret untuk data sensitif
apiVersion: v1
kind: Secret
metadata:
  name: warehouse-secret
  namespace: buroqet
  labels:
    app: warehouse-service
type: Opaque
# ⚠️ FILE INI JANGAN DI-COMMIT dengan nilai asli
stringData:
  db_password: "GANTI"
  db_user: "GANTI"