# deployments/kubernetes/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
  labels:
    app: warehouse-service
    version: "1.0"
spec:
  replicas: 2  # Minimal 2 untuk High Availability
  
  selector:
    matchLabels:
      app: warehouse-service
  
  # Rolling Update Strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Boleh ada 1 pod extra saat update
      maxUnavailable: 0  # Tidak boleh ada pod yang mati saat update (zero downtime)
  
  template:
    metadata:
      labels:
        app: warehouse-service
    
    spec:
      containers:
        - name: warehouse-service
          image: madeu30/warehouse-service:latest
          imagePullPolicy: Always
          
          ports:
            - containerPort: 8080
          
          # Environment variable dari ConfigMap dan Secret
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: warehouse-config
                  key: db_host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: warehouse-secret
                  key: db_password
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: warehouse-config
                  key: kafka_broker
          
          # Resource limits — WAJIB agar satu service tidak menghabiskan semua CPU/RAM
          resources:
            requests:
              memory: "128Mi"  # Minimum yang diminta
              cpu: "100m"      # 100m = 0.1 core
            limits:
              memory: "256Mi"  # Maksimum yang boleh dipakai
              cpu: "500m"      # Maksimum 0.5 core
          
          # Liveness Probe: "Apakah aplikasi masih hidup?"
          # Kalau ini gagal, Kubernetes RESTART pod
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15  # Tunggu 15 detik setelah container start
            periodSeconds: 20         # Cek setiap 20 detik
            failureThreshold: 3       # Restart setelah 3 kali gagal berturut-turut
          
          # Readiness Probe: "Apakah aplikasi sudah siap terima traffic?"
          # Kalau ini gagal, Kubernetes TIDAK mengirim traffic ke pod ini (tapi tidak restart)
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3