apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
spec:
  selector:
    app: warehouse-service
  
  ports:
    - protocol: TCP
      port: 8087           # Port yang diakses dari luar service
      targetPort: 8087   # Port yang didengarkan container
  
  type: ClusterIP  # Hanya bisa diakses dari dalam cluster (lewat Ingress)