pipeline {
    agent any

    environment {
        DOCKER_CREDS = 'docker-hub-credentials'
        DOCKER_IMAGE = 'arpusauri/pricing-service:latest'
        
        KUBECONFIG = 'C:/Users/aryap/.kube/config'
    }

    stages {
        stage('1. Checkout Repo') {
            steps {
                echo "=== Mengambil kode terbaru dari GitHub ==="
                checkout scm
            }
        }

        stage('2. Unit Tests') {
            steps {
                dir('pricing-service') {
                    echo "=== Menjalankan Unit Test Pricing ==="
                    bat 'go mod tidy'
                    bat 'go test -v -count=1 ./internal/...'
                }
            }
        }

        stage('3. Lint/Vet') {
            steps {
                dir('pricing-service') {
                    echo "=== Menjalankan Linter ==="
                    bat 'go vet ./...'
                }
            }
        }

        stage('4. Build Image') {
            steps {
                dir('pricing-service') {
                    echo "=== Build Docker Image Lokal ==="
                    bat "docker build -t ${env.DOCKER_IMAGE} -f deployments/Dockerfile ."
                }
            }
        }

        stage('5. Functional Tests') {
            steps {
                dir('pricing-service') {
                    echo "=== Menjalankan Functional Test (Mengakses DB/API) ==="
                    bat 'go test -v -count=1 ./tests/functional/...'
                }
            }
        }

        stage('6. Push Image') {
            steps {
                echo "=== Push Image ke Docker Hub ==="
                withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDS, passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                    bat 'docker login -u %DOCKER_USER% -p %DOCKER_PASS%'
                    bat "docker push ${env.DOCKER_IMAGE}"
                }
            }
        }

        stage('7. Deploy di Kubernetes') {
            steps {
                dir('pricing-service') {
                    echo "=== Deploy ke K8s Lokal ==="
                    bat 'kubectl --kubeconfig="C:\\Users\\aryap\\.kube\\config" apply -f deployments/kubernetes/pricing-k8s.yaml'
                }
            }
        }

        stage('8. Verify') {
            steps {
                echo "=== Verifikasi Deployment ==="
                bat 'kubectl --kubeconfig="C:\\Users\\aryap\\.kube\\config" rollout status deployment/pricing-service'
            }
        }
    }

    post {
        success {
            echo "Pipeline Pricing Service Berhasil 100%! Aplikasi sudah jalan di K8s."
        }
        failure {
            echo "Pipeline Pricing Service Gagal! Periksa log Jenkins."
        }
    }
}