// Code generated by MockGen. DO NOT EDIT.
// Source: producer.go

package mock

import (
	context "context"
	kafka "order-management-service/internal/kafka"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKafkaProducer is a mock of Producer interface
type MockKafkaProducer struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaProducerMockRecorder
}

// MockKafkaProducerMockRecorder is the mock recorder for MockKafkaProducer
type MockKafkaProducerMockRecorder struct {
	mock *MockKafkaProducer
}

// NewMockKafkaProducer creates a new mock instance
func NewMockKafkaProducer(ctrl *gomock.Controller) *MockKafkaProducer {
	mock := &MockKafkaProducer{ctrl: ctrl}
	mock.recorder = &MockKafkaProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKafkaProducer) EXPECT() *MockKafkaProducerMockRecorder {
	return m.recorder
}

// PublishOrderCreated mocks base method
func (m *MockKafkaProducer) PublishOrderCreated(ctx context.Context, event kafka.OrderCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderCreated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderCreated indicates an expected call of PublishOrderCreated
func (mr *MockKafkaProducerMockRecorder) PublishOrderCreated(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderCreated", reflect.TypeOf((*MockKafkaProducer)(nil).PublishOrderCreated), ctx, event)
}

// Close mocks base method
func (m *MockKafkaProducer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockKafkaProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKafkaProducer)(nil).Close))
}