// Code generated by MockGen. DO NOT EDIT.
// Source: order_service.go

package mock

import (
	context "context"
	model "order-management-service/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderService is a mock of OrderService interface
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method
func (m *MockOrderService) CreateOrder(ctx context.Context, req model.CreateOrderRequest) (*model.CreateOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, req)
	ret0, _ := ret[0].(*model.CreateOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder
func (mr *MockOrderServiceMockRecorder) CreateOrder(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderService)(nil).CreateOrder), ctx, req)
}

// GetOrderByAWB mocks base method
func (m *MockOrderService) GetOrderByAWB(ctx context.Context, awbNumber string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByAWB", ctx, awbNumber)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByAWB indicates an expected call of GetOrderByAWB
func (mr *MockOrderServiceMockRecorder) GetOrderByAWB(ctx, awbNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByAWB", reflect.TypeOf((*MockOrderService)(nil).GetOrderByAWB), ctx, awbNumber)
}

// ListOrders mocks base method
func (m *MockOrderService) ListOrders(ctx context.Context, req model.ListOrdersRequest) (*model.ListOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, req)
	ret0, _ := ret[0].(*model.ListOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrders indicates an expected call of ListOrders
func (mr *MockOrderServiceMockRecorder) ListOrders(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockOrderService)(nil).ListOrders), ctx, req)
}

// UpdateOrderStatus mocks base method
func (m *MockOrderService) UpdateOrderStatus(ctx context.Context, awbNumber string, req model.UpdateOrderStatusRequest) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, awbNumber, req)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus
func (mr *MockOrderServiceMockRecorder) UpdateOrderStatus(ctx, awbNumber, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderService)(nil).UpdateOrderStatus), ctx, awbNumber, req)
}

// GetOrderByTransactionID mocks base method
func (m *MockOrderService) GetOrderByTransactionID(ctx context.Context, transactionID string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByTransactionID indicates an expected call of GetOrderByTransactionID
func (mr *MockOrderServiceMockRecorder) GetOrderByTransactionID(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByTransactionID", reflect.TypeOf((*MockOrderService)(nil).GetOrderByTransactionID), ctx, transactionID)
}

// GetOrdersByCustomerID mocks base method
func (m *MockOrderService) GetOrdersByCustomerID(ctx context.Context, customerID string, page, limit int) (*model.ListOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByCustomerID", ctx, customerID, page, limit)
	ret0, _ := ret[0].(*model.ListOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByCustomerID indicates an expected call of GetOrdersByCustomerID
func (mr *MockOrderServiceMockRecorder) GetOrdersByCustomerID(ctx, customerID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByCustomerID", reflect.TypeOf((*MockOrderService)(nil).GetOrdersByCustomerID), ctx, customerID, page, limit)
}

// CancelOrder mocks base method
func (m *MockOrderService) CancelOrder(ctx context.Context, awbNumber string) (*model.CancelOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, awbNumber)
	ret0, _ := ret[0].(*model.CancelOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder
func (mr *MockOrderServiceMockRecorder) CancelOrder(ctx, awbNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderService)(nil).CancelOrder), ctx, awbNumber)
}

// MockPricingClient is a mock of PricingClient interface
type MockPricingClient struct {
	ctrl     *gomock.Controller
	recorder *MockPricingClientMockRecorder
}

// MockPricingClientMockRecorder is the mock recorder for MockPricingClient
type MockPricingClientMockRecorder struct {
	mock *MockPricingClient
}

// NewMockPricingClient creates a new mock instance
func NewMockPricingClient(ctrl *gomock.Controller) *MockPricingClient {
	mock := &MockPricingClient{ctrl: ctrl}
	mock.recorder = &MockPricingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPricingClient) EXPECT() *MockPricingClientMockRecorder {
	return m.recorder
}

// GetPrice mocks base method
func (m *MockPricingClient) GetPrice(ctx context.Context, req model.PricingRequest) (*model.PricingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrice", ctx, req)
	ret0, _ := ret[0].(*model.PricingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrice indicates an expected call of GetPrice
func (mr *MockPricingClientMockRecorder) GetPrice(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrice", reflect.TypeOf((*MockPricingClient)(nil).GetPrice), ctx, req)
}
