version: '3.9'

services: # <--- PASTIKAN ADA BARIS INI
  pricing-service: # <--- Harus menjorok masuk 2 spasi di bawah services
    build:
      context: .. # <--- Mundur ke folder pricing-service untuk cari go.mod
      dockerfile: deployments/Dockerfile
    container_name: pricing-service-test
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres.gvmknmaybejslbghzsov:HfuyrF1xd1iUVagY@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?search_path=pricing_schema