version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: oms-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oms_test_db
    ports:
      - "5433:5432"